---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
spec:
  secretName: ingress-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - "kiali.sample.stamp"
    - "app.sample.stamp"
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
