apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
spec:
  releaseName: flagger
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      version: "1.22.2"
  interval: 1h0m0s
  values:
    meshProvider: istio
    prometheus:
      install: true