---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: osdu-community
spec:
  interval: 1m0s
  url: https://community.opengroup.org/osdu/platform/deployment-and-operations/helm-charts-azure
  ref:
    branch: release/0.16
