---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    toolkit.fluxcd.io/tenant: sample-app
  name: sample-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    istio-injection: enabled
    toolkit.fluxcd.io/tenant: sample-app
  name: sample-app
  namespace: sample-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    istio-injection: enabled
    toolkit.fluxcd.io/tenant: sample-app
  name: sample-app-reconciler
  namespace: sample-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:sample-app:reconciler
- kind: ServiceAccount
  name: sample-app
  namespace: sample-app
